#### Problem Set 1 (Problem 6)
#### Description: Adaptation of Code in weighted_regression.ipynb
#### Authors: Bobing, Cassandra, Max, Prema, Rajdev, and Yazen
#### Date last modified: March 30, 2023


#### Part 2
#### Notes:
1. y = Xβ + u (simultaneous equations)
- y is Nxk matrix
- X is Nxl matrix
- u is Nxk matrix
- cov(u|X) = Ω (non-daiagonal matrix)
- X = T 
2. In the example below, we take a general case with k =3, l =2, and Ω =3x3 non-diagonal matrix 


In [45]:
%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal
import random

In [46]:
random.seed(10)

In [47]:
l = 2 # Number of observables in T

mu = [0]*l
Sigma=[[1,0.5],
       [0.5,2]]

T = multivariate_normal(mu,Sigma) # T = Nx2 matrix

In [48]:
k = 3 # number of dependent variables in y

mu = [0]*k
Sigma=[[1,0.5,0.6],
       [0.5,2,0.8],
       [0.6,0.8,3]]

u = multivariate_normal(mu,Sigma) # u = Nx3 matrix

In [49]:
beta = [[1/2,1,2],
        [1,2,1/2]]    # beta = 2x3 matrix

N=10000 # Sample size

# Now: Transform rvs into a sample
T = T.rvs(N)

u = u.rvs(N) # Replace u with a sample

X = T 

y = X@beta + u # Note use of @ operator for matrix multiplication

In [50]:
from scipy.linalg import inv, sqrtm

b = np.linalg.lstsq(T.T@X,T.T@y, rcond=None)[0] # lstsqs returns several results; we pick the first

e = y - X@b

print(b)


[[0.49198901 0.9807464  1.99842893]
 [1.01058    2.00362346 0.47711673]]


###### Sanity check: b -> beta 

In [51]:
TXplus = np.linalg.pinv(T.T@X) # Moore-Penrose pseudo-inverse

# Covariance matrix of b
vb = e.var()*TXplus@T.T@T@TXplus.T  # u is known to be homoskedastic

print(vb)

[[ 2.32521888e-04 -5.77662143e-05]
 [-5.77662143e-05  1.14998758e-04]]


#### Part 3 
#### Notes
1. Since k =3, we have 3 equations to estimate as follows: 
- y1 = Xβ1 + u1
- y2 = Xβ2 + u2
- y3 = Xβ3 + u3

In [52]:
%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal
import random
random.seed(10)

l = 2 # Number of observables in T

mu = [0]*l
Sigma=[[1,0.5],
       [0.5,2]]

T = multivariate_normal(mu,Sigma) # T = Nx2 matrix

In [53]:

u1 = multivariate_normal(cov=1) # u1 = Nx1 matrix
u2 = multivariate_normal(cov=2) # u2 = Nx1 matrix
u3 = multivariate_normal(cov=3) # u3 = Nx1 matrix


In [54]:
beta1 = [1/2,1]
beta2 = [1,2]
beta3 = [2,1/2]

N=10000 # Sample size

T = T.rvs(N)

u1 = u1.rvs(N) # Replace u1 with a sample
u2 = u2.rvs(N) # Replace u2 with a sample
u3 = u3.rvs(N) # Replace u3 with a sample

X = T 

y1 = X@beta1 + u1 # Note use of @ operator for matrix multiplication
y2 = X@beta2 + u2 
y3 = X@beta3 + u3 

In [55]:
from scipy.linalg import inv, sqrtm

b1 = np.linalg.solve(X.T@X,X.T@y1)
b2 = np.linalg.solve(X.T@X,X.T@y2)
b3 = np.linalg.solve(X.T@X,X.T@y3)

e1 = y1 - X@b1
e2 = y2 - X@b2
e3 = y3 - X@b3

vb1 = e1.var()*inv(X.T@X)
vb2= e2.var()*inv(X.T@X)
vb3 = e3.var()*inv(X.T@X)



In [56]:
print(b1, b2, b3)

[0.5025217  0.99610729] [0.98736455 1.99648165] [1.98856332 0.50218494]


In [57]:
print(np.sqrt(np.diag(vb1)), np.sqrt(np.diag(vb2)), np.sqrt(np.diag(vb3)))

[0.01073903 0.00765872] [0.01513624 0.01079467] [0.01835118 0.01308746]


#### Comparing SUR with OLS

From parts 2 and 3 above, the SUR estimates appear to be more efficient (i.e., lower variance) than the OLS estimates.   